import requests

url = "http://0.0.0.0:8000/predict"
data = {
    "Destination_Port": 49188,
    "Flow_Duration": 4,
    "Total_Fwd_Packets": 2,
    "Total_Backward_Packets": 0,
    "Total_Length_of_Fwd_Packets": 12,
    "Total_Length_of_Bwd_Packets": 0,
    "Fwd_Packet_Length_Max": 12,
    "Fwd_Packet_Length_Min": 12,
    "Fwd_Packet_Length_Mean": 12,
    "Fwd_Packet_Length_Std": 0,
    "Bwd_Packet_Length_Max": 0,
    "Bwd_Packet_Length_Min": 0,
    "Bwd_Packet_Length_Mean": 0,
    "Bwd_Packet_Length_Std": 0,
    "Flow_Bytes_per_second": 3,
    "Flow_Packets_per_second": 0.5,
    "Flow_IAT_Mean": 0.01,
    "Flow_IAT_Std": 0.1,
    "Flow_IAT_Max": 0.2,
    "Flow_IAT_Min": 0.0,
    "Fwd_IAT_Total": 4,
    "Fwd_IAT_Mean": 2,
    "Fwd_IAT_Std": 1,
    "Fwd_IAT_Max": 4,
    "Fwd_IAT_Min": 0,
    "Bwd_IAT_Total": 0,
    "Bwd_IAT_Mean": 0,
    "Bwd_IAT_Std": 0,
    "Bwd_IAT_Max": 0,
    "Bwd_IAT_Min": 0,
    "Fwd_PSH_Flags": 0,
    "Bwd_PSH_Flags": 0,
    "Fwd_URG_Flags": 0,
    "Bwd_URG_Flags": 0,
    "Fwd_Header_Length": 0,
    "Bwd_Header_Length": 0,
    "Fwd_Packets_per_second": 0.5,
    "Bwd_Packets_per_second": 0,
    "Min_Packet_Length": 12,
    "Max_Packet_Length": 12,
    "Packet_Length_Mean": 12,
    "Packet_Length_Std": 0,
    "Packet_Length_Variance": 0,
    "FIN_Flag_Count": 0,
    "SYN_Flag_Count": 0,
    "RST_Flag_Count": 0,
    "PSH_Flag_Count": 0,
    "ACK_Flag_Count": 0,
    "URG_Flag_Count": 0,
    "CWE_Flag_Count": 0,
    "ECE_Flag_Count": 0,
    "Down_Up_Ratio": 0,
    "Average_Packet_Size": 12,
    "Avg_Fwd_Segment_Size": 12,
    "Avg_Bwd_Segment_Size": 0,
    "Fwd_Header_Length_1": 0,
    "Fwd_Avg_Bytes_per_Bulk": 0,
    "Fwd_Avg_Packets_per_Bulk": 0,
    "Fwd_Avg_Bulk_Rate": 0,
    "Bwd_Avg_Bytes_per_Bulk": 0,
    "Bwd_Avg_Packets_per_Bulk": 0,
    "Bwd_Avg_Bulk_Rate": 0,
    "Subflow_Fwd_Packets": 2,
    "Subflow_Fwd_Bytes": 12,
    "Subflow_Bwd_Packets": 0,
    "Subflow_Bwd_Bytes": 0,
    "Init_Win_bytes_forward": 0,
    "Init_Win_bytes_backward": 0,
    "act_data_pkt_fwd": 2,
    "min_seg_size_forward": 0,
    "Active_Mean": 0,
    "Active_Std": 0,
    "Active_Max": 0,
    "Active_Min": 0,
    "Idle_Mean": 0,
    "Idle_Std": 0,
    "Idle_Max": 0,
    "Idle_Min": 0
}

response = requests.post(url, json=data)

print(response.json())
